"user server";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

import "@/database/initializeDatabase";
import { getSession } from "@/lib/auth.actions";

export const metadata: Metadata = {
  title: "Custom Next.js Authentication",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header role={session?.role} />
        <main className="min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
